### ISSUE TITLE
How can I download the video dataset?

### ISSUE THREAD

**Issue by J-JunChen** [VSPW-dataset/VSPW-dataset-download#2]
Hi,

When I use the command `sh video_download.sh`, the error happends.
such as,
```
downloading video:dBd8Ixkx6nI
sh: 1: youtube-dl: not found
sh: 1: youtube-dl: not found
sh: 1: youtube-dl: not found
sh: 1: youtube-dl: not found
```

**Comment by wanghao9610** [comment]
Install youtube-dl first.
Follow the link: https://ytdl-org.github.io/youtube-dl/download.html

**Comment by VSPW-dataset** [comment]
@Jun-jieChen @wanghao9610  If it is hard to download the Youtube videos, you can refer to this link https://github.com/sssdddwww2/vspw_dataset_download which extracted all the frames.

**Comment by J-JunChen** [comment]
Hi, @VSPW-dataset 
Are extracted frames the same as the Youtube videos?

**Comment by wanghao9610** [comment]
@VSPW-dataset You should update the link which extracted all the frames on README.md.

**Comment by sssdddwww2** [comment]
@Jun-jieChen Yes, the extracted frames can be directly used and you do not need download YouTube videos.

**Comment by J-JunChen** [comment]
@sssdddwww2 
Ok! Thanks a lot.

**Comment by jingliang95** [comment]
@VSPW-dataset @sssdddwww2 @wanghao9610 @Jun-jieChen 
Hello all, I found that the dataset downloaded from link (https://github.com/sssdddwww2/vspw_dataset_download) is not correct. The downloaded vspw_dataset.tar contains **251630** images (considering correct .jpg). The vspw_480p.zip contains **250412** images. However, the paper says there are a total of **251633** frames. Which is correct and which is wrong? Could you solve these inconsistency? Thanks a lot.
